name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: List current directory (Debugging)
      run: |
        echo "Current directory: $(pwd)"
        ls -la

    - name: Install dependencies in frontend
      run: |
        cd frontend
        echo "Inside frontend directory: $(pwd)"
        ls -la
        npm install

    - name: Run tests in frontend
      run: |
        cd frontend
        npm test
